(defun DEL (N LST)
   (COND ((EQ N 1) (CDR LST))
      (T (CONS (CAR LST)
            (DEL (- N 1) (CDR LST))
         )
      )
   )
)
(defun input ()
    (print "Исходный список:")
    (print L)
    (print "Введите место удаления:") 
    (set 'P (read))
    (print "Итоговый список:") 
    (set 'L(DEL P L )) 
   
    
)
(set 'L '(11 8 19 55 1 3 2 1))
(input)