(defun sch (N lst)
   (cond ((eq lst nil) "Элемент не найден.")
((eq (car lst) N) "Элемент найден.")
(t (sch N (cdr lst)))
   )
)
(defun input ()
    (print "Исходный список:")
    (print L)
    (print "Введите элемент для поиска:") 
    (set 'N (read))
    (print "Результат поиска:") 
    (sch N L)
   
    
)
(set 'L '(11 8 19 55 1 3 2 1))
(input)